# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish

on:
  release:
    types: [ prereleased, released ]
  workflow_dispatch:

env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
      - name: Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
      - name: Setup versions
        run: ./gradlew :updateVersions
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish Firebase Analytics
        run: ./gradlew :firebase-analytics:publishToMavenCentral
      - name: Publish Firebase App
        run: ./gradlew :firebase-app:publishToMavenCentral
      - name: Publish Firebase Auth
        run: ./gradlew :firebase-auth:publishToMavenCentral
      - name: Publish Firebase Common
        run: ./gradlew :firebase-common:publishToMavenCentral
      - name: Publish Firebase Common Internal
        run: ./gradlew :firebase-common-internal:publishToMavenCentral
      - name: Publish Firebase Config
        run: ./gradlew :firebase-config:publishToMavenCentral
      - name: Publish Firebase Database
        run: ./gradlew :firebase-database:publishToMavenCentral
      - name: Publish Firebase Firestore
        run: ./gradlew :firebase-firestore:publishToMavenCentral
      - name: Publish Firebase Functions
        run: ./gradlew :firebase-functions:publishToMavenCentral
      - name: Publish Firebase Messaging
        run: ./gradlew :firebase-messaging:publishToMavenCentral
      - name: Publish Firebase Storage
        run: ./gradlew :firebase-storage:publishToMavenCentral
      - name: Publish Firebase Installations
        run: ./gradlew :firebase-installations:publishToMavenCentral
      - name: Publish Firebase Performance
        run: ./gradlew :firebase-perf:publishToMavenCentral
      - name: Publish Firebase Crashlytics
        run: ./gradlew :firebase-crashlytics:publishToMavenCentral
  documentation:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
      - uses: gradle/gradle-build-action@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate documentation
        run: ./gradlew dokkaGenerate
      - name: Uploading build folder
        uses: actions/upload-artifact@v4
        with:
          name: artefact
          path: build/dokka/html
      - name: Deploy API documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/dokka/html
          target-folder: docs
